services:
  - type: web
    name: pallarescorp-backend
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgres://pallares_user:xxx@...render.com/mi_db_pallarescorp
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
