services:
  - type: web
    name: pallarescorp-backend
    env: python
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgres://pallares_user:8IdBB3JZ6Wo0rFIrpbQSrUolk86UhHj5@dpg-d25caj7diees73aujqrg-a.oregon-postgres.render.com/mi_db_pallarescorp
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
